In [1]:
from __future__ import print_function
import torch as t

In [5]:
x = t.Tensor(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
        [-2.5244e-29,  3.7170e-32,  1.4013e-45],
        [-1.8785e-01,  4.5905e-41, -1.8786e-01],
        [ 4.5905e-41,  2.4822e-33,  1.4013e-45],
        [ 2.4456e-33,  1.4013e-45,  3.0774e+36]])


In [8]:
x = t.rand(5, 3)
print(x)
print(x.size())

tensor([[0.7499, 0.1255, 0.6039],
        [0.5744, 0.1426, 0.5422],
        [0.0875, 0.1446, 0.0230],
        [0.2604, 0.5112, 0.0346],
        [0.5387, 0.2690, 0.7678]])
torch.Size([5, 3])


In [12]:
y = t.rand(5, 3)
print(y)
print(x + y)
print(t.add(x,y))

result = t.Tensor(5, 3)
t.add(x, y, out=result)
print(result)

tensor([[0.8142, 0.4091, 0.4822],
        [0.3672, 0.2741, 0.9067],
        [0.2200, 0.6586, 0.2019],
        [0.8706, 0.6062, 0.9032],
        [0.4641, 0.1444, 0.5005]])
tensor([[1.5640, 0.5346, 1.0861],
        [0.9416, 0.4167, 1.4488],
        [0.3075, 0.8033, 0.2249],
        [1.1310, 1.1174, 0.9379],
        [1.0028, 0.4134, 1.2683]])
tensor([[1.5640, 0.5346, 1.0861],
        [0.9416, 0.4167, 1.4488],
        [0.3075, 0.8033, 0.2249],
        [1.1310, 1.1174, 0.9379],
        [1.0028, 0.4134, 1.2683]])
tensor([[1.5640, 0.5346, 1.0861],
        [0.9416, 0.4167, 1.4488],
        [0.3075, 0.8033, 0.2249],
        [1.1310, 1.1174, 0.9379],
        [1.0028, 0.4134, 1.2683]])


In [13]:
print(y)

y.add(x)
print(y)

y.add_(x)
print(y)

tensor([[0.8142, 0.4091, 0.4822],
        [0.3672, 0.2741, 0.9067],
        [0.2200, 0.6586, 0.2019],
        [0.8706, 0.6062, 0.9032],
        [0.4641, 0.1444, 0.5005]])
tensor([[0.8142, 0.4091, 0.4822],
        [0.3672, 0.2741, 0.9067],
        [0.2200, 0.6586, 0.2019],
        [0.8706, 0.6062, 0.9032],
        [0.4641, 0.1444, 0.5005]])
tensor([[1.5640, 0.5346, 1.0861],
        [0.9416, 0.4167, 1.4488],
        [0.3075, 0.8033, 0.2249],
        [1.1310, 1.1174, 0.9379],
        [1.0028, 0.4134, 1.2683]])


In [14]:
print(x)
print(x[:, 1])

tensor([[0.7499, 0.1255, 0.6039],
        [0.5744, 0.1426, 0.5422],
        [0.0875, 0.1446, 0.0230],
        [0.2604, 0.5112, 0.0346],
        [0.5387, 0.2690, 0.7678]])
tensor([0.1255, 0.1426, 0.1446, 0.5112, 0.2690])


In [19]:
a = t.ones(5)
print(a)

b = a.numpy()
print(b)

import numpy as np

a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

b.add_(1)
print(a, b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [31]:
from torch.autograd import Variable
x = Variable(t.ones(2, 2), requires_grad = True)
print(x)

y = x.sum()
print(y)

print(y.grad_fn)
print(y.data)
print(x.grad)

y.backward()
print(x.grad)

x.grad.data.zero_()  # important

y.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor(4., grad_fn=<SumBackward0>)
tensor(4.)
None
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
x = Variable()