In [1]:
from __future__ import print_function
import torch as t

In [10]:
a = t.Tensor(2, 3)
print(a)

b = t.Tensor([[1, 2, 3], [4, 5, 6]])
print(b)

print(b.tolist())

print(b)

b_size = b.size()
print(b_size)
print(b.numel())

c = t.Tensor(b_size)
d = t.Tensor(2, 3)
print(c, d)

print(c.shape, d.shape)

tensor([[5.0643e+07, 4.5804e-41, 5.0643e+07],
        [4.5804e-41, 5.0514e-20, 1.4013e-45]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
6
tensor([[2.6982e+06, 4.5804e-41, 2.6982e+06],
        [4.5804e-41, 5.0832e-20, 1.4013e-45]]) tensor([[2.6982e+06, 4.5804e-41, 2.6982e+06],
        [4.5804e-41, 5.1180e-20, 1.4013e-45]])
torch.Size([2, 3]) torch.Size([2, 3])


In [17]:
print(t.ones(2, 3))
print(t.zeros(2, 3))
print(t.arange(1, 6, 2))
print(t.linspace(1, 10, 3))
print(t.randn(2, 3))
print(t.randperm(5))
print(t.eye(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[ 0.9428,  1.8616, -0.7039],
        [ 0.1909, -0.1644, -0.6421]])
tensor([3, 1, 2, 4, 0])
tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [29]:
a = t.arange(0, 6)
print(a.view(2, 3))
print(a)
b = a.view(-1, 3)
print(b)
c = b.unsqueeze(1)
print(c, c.shape)
d = b.view(1, 1, 1, 1, 2, 3)
print(d, d.shape)
print(d.squeeze())

a[1] = 100
print(b)

b.resize_(1, 3)
print(b)
b.resize_(3, 3)
print(b)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]]]) torch.Size([2, 1, 3])
tensor([[[[[[0, 1, 2],
            [3, 4, 5]]]]]]) torch.Size([1, 1, 1, 1, 2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[  0, 100,   2],
        [  3,   4,   5]])
tensor([[  0, 100,   2]])
tensor([[              0,             100,               2],
        [              3,               4,               5],
        [140390826005928, 140390826005904, 140390826005880]])


In [31]:
a = t.randn(3, 4)
print(a)

tensor([[-1.0086,  3.0326,  0.3682, -1.3417],
        [ 1.7980, -0.4934, -0.2931,  0.2001],
        [-0.8427, -0.9508, -0.1997,  0.5695]])


In [43]:
print(a[0])
print(a[:, 0])
print(a[0][2], a[0,2])
print(a[0, -1])
print(a[:2])
print(a[:2, 0:2])
print(a[0:1, :2])
print(a[0, :2])
print(a > 1)
print(a[a > 1])
print(a[t.LongTensor([0, 1])])

tensor([-1.0086,  3.0326,  0.3682, -1.3417])
tensor([-1.0086,  1.7980, -0.8427])
tensor(0.3682) tensor(0.3682)
tensor(-1.3417)
tensor([[-1.0086,  3.0326,  0.3682, -1.3417],
        [ 1.7980, -0.4934, -0.2931,  0.2001]])
tensor([[-1.0086,  3.0326],
        [ 1.7980, -0.4934]])
tensor([[-1.0086,  3.0326]])
tensor([-1.0086,  3.0326])
tensor([[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)
tensor([3.0326, 1.7980])
tensor([[-1.0086,  3.0326,  0.3682, -1.3417],
        [ 1.7980, -0.4934, -0.2931,  0.2001]])


In [44]:
a = t.arange(0, 16).view(4, 4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [46]:
index = t.LongTensor([[0, 1, 2, 3]])
print(index)
print(a.gather(0, index))

tensor([[0, 1, 2, 3]])
tensor([[ 0,  5, 10, 15]])


In [50]:
x = t.arange(0, 27).view(3, 3, 3)
print(x)
print(x[[1, 2], [1, 2], [2, 0]])
print(x[[2, 1, 0], [0], [1]])
print(x[[0, 2], ...])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([14, 24])
tensor([19, 10,  1])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [58]:
t.set_default_tensor_type('torch.FloatTensor')
a = t.Tensor(2, 3)
print(a, a.dtype)
b = a.int()
print(b, b.dtype)

c = a.type_as(b)
print(b, b.dtype)

d = c.new(2, 3)
print(d, d.dtype)

tensor([[2.6948e+06, 4.5804e-41, 2.6948e+06],
        [4.5804e-41, 5.0832e-20, 1.4013e-45]]) torch.float32
tensor([[2694784,       0, 2694784],
        [      0,       0,       0]], dtype=torch.int32) torch.int32
tensor([[2694784,       0, 2694784],
        [      0,       0,       0]], dtype=torch.int32) torch.int32
tensor([[ 678913390, 1142959146, 1667855973],
        [1679834981, 1667855973, 1867398501]], dtype=torch.int32) torch.int32


In [63]:
# 逐元素操作
a = t.arange(0, 6).view(2, 3)
a = a.float()
print(t.cos(a))
print(a  % 3)
print(a ** 2)
print(t.clamp(a, min=3))

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])
tensor([[0., 1., 2.],
        [0., 1., 2.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[3., 3., 3.],
        [3., 4., 5.]])


In [66]:
# 归并操作
b = t.ones(2, 3)
print(b.sum(dim = 0, keepdim=True))
print(b.sum(dim = 1))
a = t.arange(0, 6).view(2, 3)
print(a.cumsum(dim=1))

tensor([[2., 2., 2.]])
tensor([3., 3.])
tensor([[ 0,  1,  3],
        [ 3,  7, 12]])


In [78]:
# 比较
a = t.linspace(0, 15, 6).view(2, 3)
print(a)
b = t.linspace(15, 0, 6).view(2, 3)
print(b)

print(a > b)
print(a[a > b])

print(t.max(a))
print(t.max(a, dim = 1))
print(t.max(a, b))
print(t.clamp(a, min=10))

# linear algebra
b = a.t()
print(a, b, b.is_contiguous())
b = b.contiguous()
print(b, b.is_contiguous())

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])
tensor([[15., 12.,  9.],
        [ 6.,  3.,  0.]])
tensor([[0, 0, 0],
        [1, 1, 1]], dtype=torch.uint8)
tensor([ 9., 12., 15.])
tensor(15.)
(tensor([ 6., 15.]), tensor([2, 2]))
tensor([[15., 12.,  9.],
        [ 9., 12., 15.]])
tensor([[10., 10., 10.],
        [10., 12., 15.]])
tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]]) tensor([[ 0.,  9.],
        [ 3., 12.],
        [ 6., 15.]]) False
tensor([[ 0.,  9.],
        [ 3., 12.],
        [ 6., 15.]]) True


In [79]:
import numpy as np
a = np.ones([2, 3], dtype=np.float32)
b = t.from_numpy(a)

print(a, b)
a[0, 1] = 100
print(a, b)

[[1. 1. 1.]
 [1. 1. 1.]] tensor([[1., 1., 1.],
        [1., 1., 1.]])
[[  1. 100.   1.]
 [  1.   1.   1.]] tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]])


In [80]:
a = t.ones(3, 2)
b = t.zeros(2, 3, 1)
print(a)
print(b)
print(a + b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [93]:
a = t.arange(0, 6)
print(a, a.storage())

b = a.view(2, 3)
print(b, b.storage())

print(id(a.storage()), id(b.storage()))

a[1] = 100
print(b)

c = a[2:]
print(c.storage())

print(c.data_ptr(), a.data_ptr())
print(a.dtype)


tensor([0, 1, 2, 3, 4, 5])  0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]
tensor([[0, 1, 2],
        [3, 4, 5]])  0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]
4823025208 4823025208
tensor([[  0, 100,   2],
        [  3,   4,   5]])
 0
 100
 2
 3
 4
 5
[torch.LongStorage of size 6]
140390826902208 140390826902192
torch.int64


In [103]:
# gather and scatter
a = t.arange(0, 16).view(4, 4)
index = t.LongTensor([[0, 1, 2, 3]])
print(a)
print(a.gather(0, index))

index = t.LongTensor([[3, 2, 1, 0]]).t()
print(a.gather(1, index))

index = t.LongTensor([[3, 2, 1, 0]])
print(a.gather(0, index))

index = t.LongTensor([[0, 1, 2, 3], [3, 2, 1, 0]]).t()
b = a.gather(1, index)
print(b)

c = t.zeros(4, 4)
c = c.float()
b = b.float()
c.scatter_(1, index, b)
print(c)



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  5, 10, 15]])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]])
tensor([[12,  9,  6,  3]])
tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])
tensor([[ 0.,  0.,  0.,  3.],
        [ 0.,  5.,  6.,  0.],
        [ 0.,  9., 10.,  0.],
        [12.,  0.,  0., 15.]])
